### ISSUE TITLE
hide / deleteAll / kickMemList / kickMemRelease packet

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#10]
is there a implemented packet for those operation?

note: packet names are assumed
```
export class PacketRewriteReq extends LocoBsonRequestPacket {

    constructor(
        public ClientOpenUserId: Long = Long.ZERO,
        public ChannelId: Long = Long.ZERO,
        public LogId: Long = Long.ZERO,
        public Time: number = 0,
        public RewriteFeedType: FeedType | null = FeedType.OPENLINK_REWRITE_FEED,
        public Unknown1: string = '',
        public Unknown2: string = '',
...
```
and there are two unknown parameters in PacketRewriteReq class, is it optional, or necessary but unimplemented?

**Comment by storycraft** [comment]
Unknown params are optional and not required on sending. It's unknown values in response packet. Also you can't set RewriteFeedType anything than OPENLINK_REWRITE_FEED.

**Comment by starlesssss** [comment]
So you mean PacketRewriteReq : OPENLINK_REWRITE_FEED is 'moderator hide msg' packet?
If then, 

```
let packet = new PacketRewriteReq(channel.openLinkId, channel.channelId, chat.LogId, chat.SendTime)
```

is this the right format?

also, do you have plan to implement kickMemList / kickMemRelease packets?

**Comment by storycraft** [comment]
It's right format

No.
