### ISSUE TITLE
profileType does not work properly

### ISSUE THREAD

**Issue by kiwioverflow** [storycraft/node-kakao#103]
### **Describe the bug**
`profileType` in `memberStruct` is Not included until user profile is changed

### **To Reproduce**
1. Run the script
2. Without changing the profile, `chat.channel.userInfoMap.get(chat.sender.id.toString()).memberStruct` does not include `profileType`.
3. Change the profile to any that is not the same as before
4. Now `memberStruct`  include  `profileType`,

**Expected behavior**
Regardless of whether the profile is changed or not, `profileType` must always be included in the `memberStruct`.

**Screenshots**
![image](https://user-images.githubusercontent.com/39560346/104357962-31bb4300-5551-11eb-939a-f2ac63fd1c4b.png)

**Comment by storycraft** [comment]
See #45
