### ISSUE TITLE
chat.attachment undefined

### ISSUE THREAD

**Issue by push-ebp0** [storycraft/node-kakao#112]
**Describe the bug**
v4.0에서 chat.type이 1일경우에 chat.attachment가 {}으로 나타날때도 있고 undefined으로 나타날때도 있습니다.

**To Reproduce**
chat.attachment을 표시하게 한 후, 텍스트를 계속 보내봅니다.

**Expected behavior**
표시된 chat.attachment가 {}으로 표시

**Used Code**
```javascript
client.on("chat", (chat, channel) => {
    console.log("\n\n[+] ==== ChatLog ====");
    console.log(`  [=] Text: ${chat.text}`);
    console.log(`  [=] Type: ${chat.type}`);
    console.log(`  [=] Attachment: ${JSON.stringify(chat.attachment)}`);
});
```

**Screenshots**
![화면 캡처 2021-01-31 192400](https://user-images.githubusercontent.com/77712933/106381091-e67eac80-63f9-11eb-9ee0-e6a4f85eb50f.png)
![image](https://user-images.githubusercontent.com/77712933/106381193-702e7a00-63fa-11eb-96b1-01541789046f.png)

**Comment by storycraft** [comment]
서버에서 chatlog를 줄때 attachment 값을 빈 객체로 주는 경우가 있습니다. 위는 해당 경우 인것으로 보입니다

**Comment by push-ebp0** [comment]
attachment값을 빈 객체로 줬다고 가정하면 undefined가 나오면 안되지 않나요.
타입 1이면 빈 객체가 올텐데 어떨때는 undefined, 어떨때는 빈 객체를 넣네요

**Comment by storycraft** [comment]
변환하는 부분은 https://github.com/storycraft/node-kakao/blob/be94ebb120794486ec57769f25e67101c940fa14/src/packet/struct/wrap/chat.ts#L11 이곳에서 볼수 있습니다. 변환 과정에서 추가 처리를 하지 않습니다

**Comment by push-ebp0** [comment]
패킷을 확인해보니 attachment 자체를 안넘기는 경우도 있네요.
예전에는 attachment 줬었는데 요즘 닉네임도 안주고 변화가 있네요.
이슈를 닫겠습니다.
