### ISSUE TITLE
This device is not registered.

### ISSUE THREAD

**Issue by Charles599** [storycraft/node-kakao#12]
I installed this with `npm install node-kakao`
and my code is `const Module = require('node-kakao');`
`let TalkClient = Module.TalkClient;`
`let client = new TalkClient('TEST_CLIENT');`
`client.login('email@gmail.com', 'password', 'uuid from hxd');`
I checked my PC kakaotalk, I think my account is registered.
Can you suggest me something to do?

**Comment by storycraft** [comment]
'-100 device not registered' means login succeed but provided device_uuid is not registered one. To register specific device, request passcode. You can find some useful functions in `src/kakao-api.ts`. Or if you extracted it from official client make sure the uuid is not url encoded.

**Comment by Charles599** [comment]
Thank you very much. I solved this by decode uuid.
But can I ask you one more?
This is my code now,
![캡처](https://user-images.githubusercontent.com/47498441/81040041-70d6c600-8ee5-11ea-8f59-ff49aa63840e.PNG)
but there's error `SyntaxError: Unexpected token ':'`
Can help me again please? I'm sorry if I'm annoying you.

**Comment by storycraft** [comment]
I don't accept code question
