### ISSUE TITLE
getUserInfo Sometimes return null.

### ISSUE THREAD

**Issue by samknp** [storycraft/node-kakao#120]
reproduce
   client.on('message', (chat) => {      
        let roomName = chat.Channel.getDisplayName();  
        let userInfo = chat.Channel.getUserInfo(chat.Sender);
        if (!userInfo) return;     

getUserInfoIdMap(id) {
        console.log('getUserInfoIdMap() : ' + this.userInfoMap.get(id.toString()));        
        return this.userInfoMap.get(id.toString()) || null;
    }

versionInfo
 "dependencies": {
    "node-kakao": "^3.1.8"
  },

result
2021-02-03 9:52:493    Login succeed
getUserInfoIdMap() : undefined
getUserInfoId() : 8975495751435441196
getUserInfoIdMap() : undefined
getUserInfoIdMap() : undefined
getUserInfoId() : 7683974361248019103
getUserInfoIdMap() : undefined
getUserInfoIdMap() : undefined
getUserInfoId() : 8975495751435441196
getUserInfoIdMap() : undefined
getUserInfoId() : 8975495751435441196
getUserInfoIdMap() : undefined

Some open channels failed to getUserInfo(). 
I don't know why the this.userInfoMap is undefined.
Thanks in advance.

**Comment by samknp** [comment]
Maybe same issue with #75 I guess.

**Comment by storycraft** [comment]
I have no idea about this issue. How many users are in the open channel? Is it happening on any random channel or occurring to random user on one open channel? These things are unable to know only with attached code. There is issue template made to prevent omitting these details, also please use code blocks to wrap code.
