### ISSUE TITLE
chat.channel.getUserInfo() returns null in openchatroom upper then 1300 people.

### ISSUE THREAD

**Issue by samknp** [storycraft/node-kakao#144]
**Describe the bug**
chat.channel.getUserInfo() returns null in openchatroom upper then 1300 people.
Same as #75 

**To Reproduce**
openchatroom with more then 1300 people participated.
`
function checkText(chat){
    const userInfo = chat.Channel.getUserInfo(chat.Sender);  
}
`

**Expected behavior**
It should return information about chat.sender.

**nodekakao version**
nodekakao 3.1.8 version

**Comment by storycraft** [comment]
I changed initializing logic in #75 andh checked it working. There were some case reported Userinfo initialize failing like this. Unfortunately I don't have any "openchat" room over 1000 people.

**Comment by storycraft** [comment]
If you can, can you test if it fail same in 4.0.0-beta.5?

**Comment by ecclesia00** [comment]
4.0.0 에서는 userInfo가 잘 나옵니다만, 3.1.8 에서는 아직도 고쳐지지 않은듯 하네요

**Comment by ecclesia00** [comment]
3.1.10에서 테스트결과 잘나옵니다.

**Comment by storycraft** [comment]
#75 이후 작동하는것이 확인되었지만, 일부 채팅방에서 제대로 작동하지 않는듯 합니다.

**Comment by samknp** [comment]
> 3.1.10에서 테스트결과 잘나옵니다.

3.1.8 버전 이후로는 4.0.5 beta로 넘어가는거 아닌가요?
3.1.10 버전도 있나요?

**Comment by ecclesia00** [comment]
> > 3.1.10에서 테스트결과 잘나옵니다.
> 
> 3.1.8 버전 이후로는 4.0.5 beta로 넘어가는거 아닌가요?
> 3.1.10 버전도 있나요?

3.1.10 어제인가 오늘 나왔습니다.

> #75 이후 작동하는것이 확인되었지만, 일부 채팅방에서 제대로 작동하지 않는듯 합니다.

아마 3.1.10에서도 일부 채팅방에서는 제대로 작동하지 않을 수 있습니다.

**Comment by samknp** [comment]
> If you can, can you test if it fail same in 4.0.0-beta.5?

Sure. I already ready to test with 4.0.5 version.
I will report here after the testing.

**Comment by samknp** [comment]
> If you can, can you test if it fail same in 4.0.0-beta.5?

It returns undefined. in node-kakao@4.0.0-beta.4 And also 3.1.10.
Same Issue.

**Comment by samknp** [comment]
추가 테스트 결과
1301명까지 pass
1321명이상 fail
100% 재현 이슈

**Comment by storycraft** [comment]
커밋 bd18590b33b67ae6aa25717f08007645f99fae20 이후 1400+명 방에서 작동 확인했습니다. rc.4 버전에서 다시 테스트 부탁드립니다

**Comment by samknp** [comment]
> 커밋 [bd18590](https://github.com/storycraft/node-kakao/commit/bd18590b33b67ae6aa25717f08007645f99fae20) 이후 1400+명 방에서 작동 확인했습니다. rc.4 버전에서 다시 테스트 부탁드립니다

1336명방, 4.0.0_RC4 에서 테스트 결과
타인이 이야기 한것은 정상 리턴(기존에 undefined로 리턴하던 오류 수정됨)
그러나 본인(로그인 된 계정)이 이야기 할 경우 여전히 undefined 로 리턴됨.
1300명 이하 방에서는 본인이 이야기 해도 userInfo 정상적으로 리턴됨
1300명 이상 방에서만 본인이 이야기 할 경우 undefined로 리턴됨.
