### ISSUE TITLE
Loop Auto Logout Error

### ISSUE THREAD

**Issue by Mage-Megumin** [storycraft/node-kakao#16]
![image](https://user-images.githubusercontent.com/64342999/81644218-4abfa180-9462-11ea-920d-f42b7143774f.png)

I get a message that I'm logged in, but I'm still logged out.

**Comment by delta-kor** [comment]
Check if the login task has been rejected.

```javascript
const login = client.login(...);
login.then(() => console.log('Logined Successfully');
login.catch((e) => console.error(e));
```

**Comment by Mage-Megumin** [comment]
> Check if the login task has been rejected.
> 
> ```js
> const login = client.login(id, pass, uuid);
> login.then(() => console.log('Logined Successfully');
> login.catch((e) => console.error(e));
> ```

Result is equal

**Comment by storycraft** [comment]
Cannot reproduce bug.

**Comment by Mage-Megumin** [comment]
locoManager: LocoManager {
      locoSocket: [LocoSecureSocket],
      expireTime: 600,
      handler: [TalkPacketHandler],
      locoConnected: false,
      locoLogon: false
    }

**Comment by Mage-Megumin** [comment]
Logout Try -> Error: Not logon at TalkClient.logout

**Comment by Mage-Megumin** [comment]
@storycraft plz fix error
