### ISSUE TITLE
UNKNOWN disconnect when reading message 'device login notification'

### ISSUE THREAD

**Issue by LeeHyKu** [storycraft/node-kakao#17]
all parameters are perfact, successful login, but if read message 'device login notification' send by KakaoTalk, force disconnect by UNKNOWN reason

**Comment by Mage-Megumin** [comment]
Me too

**Comment by Mage-Megumin** [comment]
If you know how, let me know.

**Comment by keli-kor** [comment]
Please Change Kakaotalk version.

**Comment by storycraft** [comment]
CHATINFO returns with status -401 which breaks current fetch method

**Comment by storycraft** [comment]
temporary fix committed on 16b5813abeca6b02ebf928ed1505173a2e5d4a6a

**Comment by Mage-Megumin** [comment]
> temporary fix committed on [16b5813](https://github.com/storycraft/node-kakao/commit/16b5813abeca6b02ebf928ed1505173a2e5d4a6a)

It keeps logging out even after updating.

**Comment by Mage-Megumin** [comment]
> > temporary fix committed on [16b5813](https://github.com/storycraft/node-kakao/commit/16b5813abeca6b02ebf928ed1505173a2e5d4a6a)
> 
> It keeps logging out even after updating.

    locoManager: LocoManager {
      locoSocket: [LocoSecureSocket],
      expireTime: 600,
      handler: [TalkPacketHandler],
      locoConnected: false,
      locoLogon: false
    }

**Comment by storycraft** [comment]
Please go to #16 for logout issue.

**Comment by storycraft** [comment]
Closing issue.
