### ISSUE TITLE
Loop Pending Promise.

### ISSUE THREAD

**Issue by Mage-Megumin** [storycraft/node-kakao#18]
Promise still pending.
![image](https://user-images.githubusercontent.com/64342999/81675048-23c89600-9489-11ea-9384-a35a70fdd8a6.png)

Only Pending.

**Comment by Seia-Soto** [comment]
I don’t think this issue is well done and you may need to use IP assigned for home network as well. I think you should give some more information such as code snippet to resolve this issue.

**Comment by Mage-Megumin** [comment]
> I don’t think this issue is well done and you may need to use IP assigned for home network as well. I think you should give some more information such as code snippet to resolve this issue.

const Module = require('node-kakao');
let TalkClient = Module.TalkClient;
let client = new TalkClient('DESKTOP-NQ49GHF');

KakaoAPI = Module.KakaoAPI;
ChatType = Module.ChatType;
ChatMention = Module.ChatMention;
Chat = Module.Chat;
ChatChannel = Module.ChatChannel;
ChatUser = Module.ChatUser;
ChatFeed = Module.ChatFeed;

id = '--';
pass = '--';
uuid = --;

client.login(id, pass, uuid);

client.on('message', (chat = Chat) => {
    if (chat.Text === 'F테스트') {
        chat.replyText('안녕하세요 ', new ChatMention(chat.Sender)); // Ex) 안녕하세요 @storycraft
        //chat.Channel.sendTemplate(new AttachmentTemplate(ReplyAttachment.fromChat(chat), '안녕하세요')); // 답장형식
    }
});

**Comment by storycraft** [comment]
Tested with same code. It works as intended.

`client.LocoLogon === true`
`F테스트 -> 안녕하세요 @storycraft`

**Comment by Mage-Megumin** [comment]
> Tested with same code. It works as intended.
> 
> `client.LocoLogon === true`
> `F테스트 -> 안녕하세요 @storycraft`

Nani? Im Only Pending and LocoLogon == false

**Comment by Seia-Soto** [comment]
If you're connecting from runkit or similar platforms, the connection to KakaoTalk may be blocked because your connection seems abnormal and it cannot be made from a normal user. So, you may test your code in a more stable environment such as your home. There is no issue detected even for me.

**Comment by Mage-Megumin** [comment]
It keeps turning off even if I log in from the node.

**Comment by Mage-Megumin** [comment]
Win
