### ISSUE TITLE
How to Send KakaoLink?

### ISSUE THREAD

**Issue by Mage-Megumin** [storycraft/node-kakao#20]
node-kakao Have custom-attachment.js.
this is KakaoLink attachment.
How to Send KakaoLink?

**Comment by delta-kor** [comment]
```typescript
const custom = new CustomAttachment(Info: CustomInfo, Content?: CustomContent, LinkInfo?: KakaoLinkInfo);
const attachment = new AttachmentTemplate(custom);
await chat.replyAttachment(attachment);
```

**Comment by Mage-Megumin** [comment]
> ```ts
> const custom = new CustomAttachment(Info: CustomInfo, Content?: CustomContent, LinkInfo?: KakaoLinkInfo);
> const attachment = new AttachmentTemplate(custom);
> await chat.replyAttachment(attachment);
> ```

I don't know how to use it.

**Comment by Mage-Megumin** [comment]
> > ```ts
> > const custom = new CustomAttachment(Info: CustomInfo, Content?: CustomContent, LinkInfo?: KakaoLinkInfo);
> > const attachment = new AttachmentTemplate(custom);
> > await chat.replyAttachment(attachment);
> > ```
> 
> I don't know how to use it.

i'm stupid

**Comment by storycraft** [comment]
Please stop asking code question on issue tracker
