### ISSUE TITLE
인원적은 방에서 강퇴시 userInfo undefined

### ISSUE THREAD

**Issue by jinsung99** [storycraft/node-kakao#224]
4명있는 방에서 한명 내보냈더니 계속 data.getSenderInfo(channel)이 undefined를 리턴합니다.
규모있는 방에서는 발생하지 않습니다

**Comment by jinsung99** [comment]
확인결과, 방 규모가 문제가 아니라 강퇴한 관리자의 userInfo가 안뜹니다

**Comment by storycraft** [comment]
오픈채팅에서 특정 유저가 킥 되었을시 킥 된 유저가 아닌 강퇴한 유저의 userInfo를 제거하는 버그와 추가로 발견된 채팅방에 새로 참여한 유저(들)의 userInfo가 제대로 추가되지 않는 버그를 수정했습니다. 버전을 4.1.3으로 업데이트 해주세요.

**Comment by cjh980402** [comment]
> 오픈채팅에서 특정 유저가 킥 되었을시 킥 된 유저가 아닌 강퇴한 유저의 userInfo를 제거하는 버그와 추가로 발견된 채팅방에 새로 참여한 유저(들)의 userInfo가 제대로 추가되지 않는 버그를 수정했습니다. 버전을 4.1.3으로 업데이트 해주세요.

혹시 " 채팅방에 새로 참여한 유저(들)의 userInfo가 제대로 추가되지 않는 버그" 완전히 수정됐나요? 4.1.3 인데 2명있는 채팅방에서 내보내기 후 다시 참가하면 userInfo가 undefined가 뜹니다.
