### ISSUE TITLE
Auto reconnect when internet connection unstable

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#24]
If internet disconnects on an unstable network, the connection would not resume even after network reconnection. It would be nice to have such 'auto reconnect' feature.

**Comment by delta-kor** [comment]
There's an event 'disconnect' on ``` TalkClient ```

```typescript
const client: TalkClient = new TalkClient('client');
client.on('disconnect', () => {});
```

**Comment by storycraft** [comment]
There's an event 'disconnect' as @delta-kor said. From v2.1 #25 relogin method in TalkClient can be used to refresh session if user didn't logout manually.
