### ISSUE TITLE
TEXT 전송 시 sendMedia 에러

### ISSUE THREAD

**Issue by cjh980402** [storycraft/node-kakao#252]
**Describe the bug**
```
await channel.sendMedia(KnownChatType.TEXT, {name: "text",data: Buffer.from(" " + "👍".repeat(2005))});
```

위와 같은 코드 사용 시 아래와 같은 에러 발생
```
TypeError: Cannot read property 'type' of undefined
    at Object.structToChatlog (.../node-kakao/dist/packet/struct/wrap/chat.js:21:26)
    at Object.finish (.../node-kakao/dist/talk/channel/talk-channel-session.js:333:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.finish (.../node_modules/node-kakao/dist/talk/channel/talk-channel-data-session.js:128:44)
    ...
```

**Expected behavior**
해당하는 텍스트가 전송돼야함

**Comment by ecclesia00** [comment]
전송해보니 status -500 나오네요.

**Comment by ecclesia00** [comment]
보아하니 text에 byteLength로 어느 지점을 넘어가면 전송이 안되는것 같습니다.
다음 소스를 사용하여 확인하였습니다.
```ts
	if (data.text === "!test") {
		const attachment = await AttachmentApi.upload(
			1,
			"text",
			Buffer.from(" " + "👍".repeat(2005))
		);
		const builder = new ChatBuilder();
		if (attachment.success) {
			builder.attachment(attachment.result);
			builder.text(" " + "👍".repeat(2004));
			void channel
				.sendChat(builder.build(1))
				.then((e) => console.log(e));
		}
	}
```

**Comment by storycraft** [comment]
서버측 제한이므로 이슈 닫음.

**Comment by JellyBrick** [comment]
> 서버측 제한이므로 이슈 닫음.

https://github.com/DV8FromTheWorld/JDA/blob/1dad81d1e5c8bc5f1524ba12efbc555d2e684fba/src/main/java/net/dv8tion/jda/api/EmbedBuilder.java#L122-L123

JDA (Java Discord API)에서처럼,
메시지가 서버 측 제한보다 길때 Exception 던지는 것은 어떨까요?

**Comment by storycraft** [comment]
> 
> https://github.com/DV8FromTheWorld/JDA/blob/1dad81d1e5c8bc5f1524ba12efbc555d2e684fba/src/main/java/net/dv8tion/jda/api/EmbedBuilder.java#L122-L123
> 
> JDA (Java Discord API)에서처럼,
> 메시지가 서버 측 제한보다 길때 Exception 던지는 것은 어떨까요?

공식 제공되는 API가 아니기 때문에 NodeKakao에서는 제한 또는 필터링을 하지 않습니다. 또한 이미 CommandResult 객체를 통해 모든 요청에 대한 성공 유무와 상태 코드를 제공하고 있습니다.
