### ISSUE TITLE
better mention attachment

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#27]
Current version only can append mention to end of message text.
What about sending a format array to format?

ex) 
let mention = new ChatMention(chat.Sender);
let mentionContent = ['안녕하세요 ', mention, '님!'];
chat.Channel.sendTemplate(new AttachmentTemplate(MentionAttachment.fromArray(mentionContent ));

**Comment by storycraft** [comment]
Use destructuring instead.

**Comment by storycraft** [comment]
Also you can append ChatMention to AttachmentTemplate
