### ISSUE TITLE
chat.hide()

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#28]
at open-chat-manager.ts

current code:
let res = await this.Client.NetworkManager.requestPacketRes<PacketRewriteRes>(new PacketRewriteReq(channel.LinkId, channel.Id, logId, Math.floor(Date.now() / 1000), FeedType.OPENLINK_REWRITE_FEED));

Math.floor(Date.now() / 1000) should be fixed to 1.

I captured the loco packet and it sends 1, not current unix.

The hide function will not work sometimes if sent current unix.

**Comment by JellyBrick** [comment]
@starlesssss 이슈 양식 맞춰서 다시 넣어주세요.
