### ISSUE TITLE
-100  로그인 오류

### ISSUE THREAD

**Issue by gdl-blue** [storycraft/node-kakao#303]
```javascript
  const api = await AuthApiClient.create('sjedksa', '***');
  const loginRes = await api.login({
    email: '***@gmail.com',
    password: Buffer.from('***==', 'base64') + '',
  });
  console.log(loginRes);
```

```
{ status: -100, success: false }
(node:4516) UnhandledPromiseRejectionWarning: Error: Web login failed with status: -100
```

예제 코드에 나와있는 대로(근데 process.env에 값이 없어서 직접 적었읍니다) 한 코드입니다

(아 그리고 혹시 한국어 설명서는 없나요?)

윈도우 7, Node.js 13.14.0 씁니다

**Comment by storycraft** [comment]
이 예제를 참고해서 최초 로그인 전 기기등록을 먼저 해주세요.
https://github.com/storycraft/node-kakao/blob/9b0992a7b0b17c3313eac27896e93d7eec5f6ebd/examples/device-registration.ts

현재 한국어 설명서는 없습니다.

**Comment by dn1t** [comment]
![image](https://user-images.githubusercontent.com/45326612/117428574-2ad19980-af61-11eb-8e99-b78e40a85282.png)
에러코드임미다참고하심시오

**Comment by gdl-blue** [comment]
감사합니다 기기인증 잘 받았읍니다
