### ISSUE TITLE
[Question] Is it possible to use on macOS?

### ISSUE THREAD

**Issue by morishjs** [storycraft/node-kakao#305]
Hi

I went over the source code but it seems not possible to use on macOS (I found out that a agent field in a request is filled with 'win32')

Are there any ways to develop on macOS or linux-based device?

**Comment by morishjs** [comment]
No matter what a agent field has, I found it works on even macOS

**Comment by storycraft** [comment]
If you want to change agent field or other config, you can override default config via TalkClient constructor. Not recommend this because each agent uses different X-VC methods.
