### ISSUE TITLE
is there any feature to send checkbox-like message?

### ISSUE THREAD

**Issue by morishjs** [storycraft/node-kakao#318]
![image](https://user-images.githubusercontent.com/6479241/118383286-722de900-b637-11eb-858e-24f39e3ecdf4.png)
![image](https://user-images.githubusercontent.com/6479241/118383377-16179480-b638-11eb-8a64-a413991426f7.png)

Hi.
Above first screenshot illustrates a facebook postback message and secend is from the old version client. Is there a feature that a user can interact through buttons?

**Comment by storycraft** [comment]
Sending KakaoLink message (rich message type with buttons or images) with NodeKakao was possible but it is not possible(blocked by Kakao) now due to high rate of abusing . Second one is strictly limited to KakaoTalk Channel(previously Plus chat) chatroom.
