### ISSUE TITLE
소켓 연결 끊김 ECONNRESET

### ISSUE THREAD

**Issue by samknp** [storycraft/node-kakao#383]
**Describe the bug**
로그인 시점이 아닌 런타임 중에도 아래 에러가 발생합니다.

윈도우 vs code의 터미널에서 실행중이었고, 로그인 한지 12시간 흐른 뒤였습니다.
SM-T976N 안드로이드 10.0 카카오 9.2.1 셋팅입니다.

정확히 어떤 코드에서 문제가 나는지는 로그 상으로는 확인이 불가능 합니다.
런타임중에 발생했고 몇번째 라인에서 발생했는지 표시해 주지 않아서 입니다.

지금까지 2~3번정도 재현되었는데 더 자세한 내용 발견할 경우 추가적으로 글 남기도록 하겠습니다.

#304 와 비슷한 에러메시지인데, 저도 로그인시 같은 에러가 있었습니다.

그때는, 노트북에서 휴대폰 5g테더링 연결 후 카톡방 입장이 많이 된 아이디에서 로그인 시도할 경우 발생 했었습니다.
lan에서 로그인 시도 하니 정상적으로 처리 되었습니다.

**To Reproduce**
1. Socket listening on chat event
2. Message 처리
3. 5~18시간 대기

**Expected behavior**
Socket 연결 끊김이 없어야 한다.

**Screenshots**
![image](https://user-images.githubusercontent.com/25787876/121272998-374f6600-c902-11eb-80db-e9bf29dcc9b7.png)

2021-06-09 08:41:30:4130 [INFO] - Client error!! err: Error: read ECONNRESET
2021-06-09 08:41:30:4130 [INFO] - Client error!! err: Error: read ECONNRESET
(node:11408) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11408) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:209:20)
(node:11408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by JellyBrick** [comment]
https://github.com/storycraft/node-kakao/discussions/271#discussioncomment-716599 참고하시면 좋을 것 같아요

**Comment by samknp** [comment]
> [#271 (comment)](https://github.com/storycraft/node-kakao/discussions/271#discussioncomment-716599) 참고하시면 좋을 것 같아요

소켓버퍼 싸이즈가 로그인시 뿐만 아니라 런타임중에도 유효할 수 있단 말씀이시져?

**Comment by samknp** [comment]
`src/network/loco-packet-codec.ts`
여기서 new ArrayBuffer 사이즈를 22에서 더 늘려주면 될까요?

**Comment by ecclesia00** [comment]
> `src/network/loco-packet-codec.ts`
> 여기서 new ArrayBuffer 사이즈를 22에서 더 늘려주면 될까요?

22는 Header Size이라서 늘리면 안됩니다 ㅜㅜ..

**Comment by samknp** [comment]
네트웍 공부좀 하고 오겠습니다. 답변 감삽니다..

**Comment by ecclesia00** [comment]
push_packet 이라는 이벤트 명을 사용해서 이벤트를 달아보셔서 끊기기 전 마지막으로 온 Packet의 이름과 데이터를 확인해보시길 바랍니다.

예시)
```ts
talkClient.on("push_packet", (m, d) => console.log(`[Packet] ${m} ${JSON.stringify(d, null, 2)}`));
```

**Comment by samknp** [comment]
> push_packet 이라는 이벤트 명을 사용해서 이벤트를 달아보셔서 끊기기 전 마지막으로 온 Packet의 이름과 데이터를 확인해보시길 바랍니다.
> 
> 예시)
> 
> ```ts
> talkClient.on("push_packet", (m, d) => console.log(`[Packet] ${m} ${JSON.stringify(d, null, 2)}`));
> ```

그랜절 올리옵나이다... 
패킷 로그는 따로 저장해야겠네요.

**Comment by generalxd** [comment]
저도 같은증상입니다. push_packet 찍어봐도
뜬금없는 메시지 패킷이 마지막 받은 패킷입니다..

도와주세요 중요한문제입니다.

**Comment by ecclesia00** [comment]
임시 방편으로 연결이 끊겼을때 재 로그인 하시는것을 추천드립니다.

**Comment by generalxd** [comment]
> 임시 방편으로 연결이 끊겼을때 재 로그인 하시는것을 추천드립니다.

disconnect 이벤트를 붙여놔도 패킷이안오네요 ㅜ

**Comment by generalxd** [comment]
@jongryongjeong 혹시 어떻게해결하셨는지 알수있을까요 ?

**Comment by generalxd** [comment]
etc/sysctl.conf 수정했더니 해결됐습니다.

**Comment by samknp** [comment]
> etc/sysctl.conf

저는 임시방편으로 재로그인 중이었습니다.
수정사항 공유해 주실 수 있나요?

**Comment by generalxd** [comment]
> > etc/sysctl.conf
> 
> 저는 임시방편으로 재로그인 중이었습니다.
> 수정사항 공유해 주실 수 있나요?

net.ipv4.tcp_rmem = 10240 87380 67108864
net.ipv4.tcp_wmem = 10240 87380 67108864
net.ipv4.tcp_mem = 10240 87380 67108864

net.core.rmem_max = 67108864
net.core.wmem_max = 67108864
net.core.rmem_default = 67108864
net.core.wmem_default = 67108864
net.core.optmem_max = 67108864

수정하시고
sudo sysctl -p
입력시 바로적용됩니다.

**Comment by samknp** [comment]
> > > etc/sysctl.conf
> > 
> > 
> > 저는 임시방편으로 재로그인 중이었습니다.
> > 수정사항 공유해 주실 수 있나요?
> 
> net.ipv4.tcp_rmem = 10240 87380 67108864
> net.ipv4.tcp_wmem = 10240 87380 67108864
> net.ipv4.tcp_mem = 10240 87380 67108864
> 
> net.core.rmem_max = 67108864
> net.core.wmem_max = 67108864
> net.core.rmem_default = 67108864
> net.core.wmem_default = 67108864
> net.core.optmem_max = 67108864
> 
> 수정하시고
> sudo sysctl -p
> 입력시 바로적용됩니다.

감사합니다

**Comment by mschadev** [comment]
윈도우에서는 어떻게 하는건가요? 찾아봐도 잘 안나오네요.

**Comment by wiresharkkkk** [comment]
> 윈도우에서는 어떻게 하는건가요? 찾아봐도 잘 안나오네요.

저도 궁금합니다 해결하셨나여?
