### ISSUE TITLE
로그인후 좀 지나면 이벤트를 받지못하는 현상 . 

### ISSUE THREAD

**Issue by generalxd** [storycraft/node-kakao#391]
Describe the bug
Ex) Reading CustomAttachment crashes client.

To Reproduce
Steps to reproduce the behavior.
Ex)

로그인후 시간이 지나면
더이상 메시지를 받지 못하는현상(다른 에러발생X)

OS를 옮겨도 소켓버퍼를 키워도
동일증상입니다.

계정 로그인후 하루정도 지나면
그냥 먹통됩니다.

에러로그도 안뜹니다..

push_packet으로 패킷받아봐도 그냥 정상패킷오다가 뚝 끊깁니다.

방이 15개정도 들어가있고 100% 재현이슈입니다.

Expected behavior
Ex) 'message' event with CustomChat object.
이벤트메시지가 계속 와야함

Screenshots
![image](https://user-images.githubusercontent.com/85729454/121661235-f6f90f00-cade-11eb-9994-917da904140e.png)

**Comment by storycraft** [comment]
이슈 내용과 제목 . 으로 바꾸지 마세요. 해당 이슈 내용은 복구합니다.

**Comment by starlesssss** [comment]
그래서 무슨 문제셨나요? 저도 최근 비슷한 현상이 발생하는데 이유를 모르겠네요

**Comment by generalxd** [comment]
@starlesssss 단순히 유효하지않은 패킷을 계속 보내서 그랬었습니다

**Comment by ghost** [comment]
조금 더 자세하게 설명해주실수있을까요?
