### ISSUE TITLE
'cannot read property' error in 'media-manager'

### ISSUE THREAD

**Issue by LeeHyKu** [storycraft/node-kakao#41]
**Describe the bug** 
In my case, an error of "TS2662, cannot read property 'name' of undefined" occurred.

**Expected behavior** 
https://github.com/storycraft/node-kakao/blob/50b3d66a95a631b896a0e7244542b4508f70484d/src/talk/media/media-manager.ts#L45
I changed it to 'template.name' and it was solved.

**Comment by storycraft** [comment]
Please use bug report template.

**Comment by storycraft** [comment]
@LeeHyKu 모르고 있었네요
