### ISSUE TITLE
로그인시 -203 Error

### ISSUE THREAD

**Issue by generalxd** [storycraft/node-kakao#415]
**Describe the bug**
Ex) Reading CustomAttachment crashes client.

전달하는 BODY가 바뀐건지
로그인 시도시 Login failed -203 에러를 내뱉고 다시 로그인시 정상로그인 됨

50% 재현이슈

**To Reproduce**
Steps to reproduce the behavior.
Ex) 
1. Send CustomAttachment from another device.
2. Client processes that message.
3. Errors occur

**Expected behavior**
Ex) 'message' event with CustomChat object.

**Screenshots**

**Comment by samknp** [comment]
저도 오늘부터 같은 현상 발생중입니다.

**Comment by JellyBrick** [comment]
<table>
<tr>
	<td>에러 코드
	<td>에러 ID
	<td>에러 원인
<tr>
	<td>-203
	<td>INVALID_PARAM
	<td>잘못된 변수명/타입 또는 최대 업로드 사이즈 초과
</table>

**Comment by generalxd** [comment]
> 에러 코드	에러 ID	에러 원인
> -203	INVALID_PARAM	잘못된 변수명/타입 또는 최대 업로드 사이즈 초과

로그인할때 발생하는데 어떻게 바꿔줘야할까요

**Comment by generalxd** [comment]
> 에러 코드	에러 ID	에러 원인
> -203	INVALID_PARAM	잘못된 변수명/타입 또는 최대 업로드 사이즈 초과

왜 이 에러가 발생하는지 도저히 감을못잡겠습니다..

**Comment by storycraft** [comment]
픽스 완료
