### ISSUE TITLE
add 'OpenProfileType' to 'OpenUserInfo'

### ISSUE THREAD

**Issue by LeeHyKu** [storycraft/node-kakao#45]
check if user is...
- normal user
- anon user
- open user

**Comment by storycraft** [comment]
<s>It's removed because indeterminable</s>. Use hasOpenProfile to check if user have OpenLink profile.
*removed because ambiguous sentence.

**Comment by LeeHyKu** [comment]
it can't check 'anon' or 'normal' profile

**Comment by storycraft** [comment]
> It's removed because indeterminable. Use hasOpenProfile to check if user have OpenLink profile.

The server doesn't send any information about it.

**Comment by LeeHyKu** [comment]
oh
