### ISSUE TITLE
feat(event): events as an enum

### ISSUE THREAD

**Issue by jjangga0214** [storycraft/node-kakao#456]
안녕하세요, 좋은 패키지 공유해주셔서 감사합니다.

`switch_server`, `disconnected`, `error` 등의 여러 이벤트가 있습니다.

https://github.com/storycraft/node-kakao/blob/89f1d0f4854f26045129fc1317d00e74d2de9a39/examples/events.ts#L20-L30

현재는 이와 같이 string 으로 사용해야 하는데, enum 을 사용할 수 있게하면 어떨까요?

현재도 유효한 event 이름만 사용 가능하도록 컴파일러 추론이 되긴 하는데, 따로 event enum 이 있으면 
1. 라이브러리 소비시 event 목록이 필요한 경우 간단히 import 할 수 있어 좋고, 
2. 라이브러리를 확장할 때도 유리할 수 있다고 생각합니다.
<small>(물론 과도한 일반화는 안티패턴일 수 있지만, 이 케이스는 그 정도는 아니라 생각되네요.). </small>

감사합니다.

**Comment by storycraft** [comment]
위에서 말하셨듯이 이미 이곳에 컴파일러 추론을 위한 처리가 되어있습니다. https://github.com/storycraft/node-kakao/blob/f5465d22da4e49652e6450a9b3201711c1938fcb/src/talk/event/index.ts#L26-L154

현재 NodeKakao에서는 채팅타입, 요청 오류 코드 등에 enum을 사용하고 있습니다. 하지만 event enum은 따로 필요하다 생각하고 있지 않습니다.

아래는 KnownChatType enum을 사용하는 코드와 KnownChatType enum을 사용하지 않고 챗 타입을 걸러내는 코드 입니다.
```typescript
const chat: Chat; // Assume this is valid Chat object.

if (chat.type === KnownChatType.TEXT) {
  console.log('This chat is text type');
}

if (chat.type === 1) {
  console.log('This chat is text type');
}
```
둘 다 작동하는 코드지만 enum을 사용한 것이 더 보기 좋습니다.

아래는 이벤트 등록시 이벤트 타입에 enum을 사용한 코드와 그렇지 않은 코드 입니다.
```typescript

// events.ts
export enum ClientEvents {

  DISCONNECTED = 'disconnected',
  SWITCH_SERVER = 'switch_server'

};

// main.ts
import { ClientEvents } from './events';

const CLIENT: TalkClient; // Assume this is valid TalkClient object.

CLIENT.on(ClientEvents.DISCONNECTED, (reason) => { 
   console.log(`Disconnected!! reason: ${reason}`); 
 }); 

CLIENT.on('disconnected', (reason) => { 
   console.log(`Disconnected!! reason: ${reason}`); 
 });
```
오히려 enum을 사용한 코드가 더 길고 events.ts 모듈 import도 해야합니다. 또한 ClientEvents enum 을 보시면 key와 value가 사실상 같습니다. 따라서 사용할 필요가 없습니다. 라이브러리 확장시 유리한 것도 없고 event enum을 제공할 필요가 전혀 없어 보입니다.

**Comment by jjangga0214** [comment]
@storycraft 답변 감사합니다. 말씀하시는 포인트를 충분히 공감하고 이해합니다. 그런데 부연설명을 한번 읽어주시고 다시 답변 주신다면 더 감사할 것 같습니다.

> 1. 라이브러리 소비시 event 목록이 필요한 경우 간단히 import 할 수 있어 좋고,

제가 말씀드렸던 라이브러리 소비는 단순히 `client.on()` 을 호출하는 것이 아니었습니다. 그 정도라면 이미 자동완성이 되니 문제가 없을 것입니다. 쟁점은 event 목록을 간단히 import 할 수 있어 좋다는 장점입니다.

node-kakao 를 사용해 카카오톡을 다루면서 각 개발자(소비자)가 구축하는 독자적인 프로그램에서 event 를 다루는 로직이 필요할 수 있습니다. 

상황은 다양할 수 있지만, 아주 간단한 예를 들어보겠습니다. event 발생시 그 시점을 (어디든) 기록하고 필요시 다시 정보를 불러와서 기간별로 특정 이벤트들이 발생한 횟수 등 통계를 내본다고 해보겠습니다. 가상의 pseudo-function 을 생각해보면 `save(eventName, time)`, `fetch(eventName, from, to)` 등이 있을 수 있겠습니다.

`client.on()` 은 자동완성이 되겠지만, 그 밖의 코드인 `save` 나 `fetch` 등 에서는 그런것이 없지요. 개발자가 타입을 지정해야 합니다. string 으로 하드코딩할 수도 있겠지만, 사실상 enum 이던 const enum 이던 JSON 이던 array 이던 뭔가 reference 가 가능한 data structure 를 새로 만들어야 할 것입니다.

그런데 이걸 직접 만들면 `node-kakao` 를 업데이트 하면서 event 이름이나 목록이 바뀌면 out-of-sync 가 날 수도 있겠죠.
이를 방지하려면 아래와 같이 `keyof XXXEvents` 와 같은 구문을 사용하는 등의 과정을 거칠 것입니다.

```ts
import { ClientEvents } from "node-kakao/talk/event";

const Events: { [P in keyof ClientEvents<null, null>]: P } = {
  chat: "chat",
  chat_read: "chat_read",
  chat_deleted: "chat_deleted",
  channel_added: "channel_added",
  // and more ...
};
```

이것도 object 니 type-safety 가 가능하지, enum 은 불가능하므로 수동으로 작성하고 항상 업데이트마다 sync 를 수작업으로 확인해야 합니다.

그런데 만일 node-kakao 가 그냥 enum 을 export 한다면?
그러면 깔끔하게 import 한번으로 사용할 수 있게 되니 편리하겠다는 생각이었습니다. 

> 아래는 이벤트 등록시 이벤트 타입에 enum을 사용한 코드와 그렇지 않은 코드 입니다.
> 오히려 enum을 사용한 코드가 더 길고 events.ts 모듈 import도 해야합니다. 

맞습니다. 인자의 타입으로 enum 만 허용한다면 그러한 단점이 있지요.
하지만, string 도 허용할 수 있습니다. 즉, 타입추론이 되면서 `client.on` 을 기존에 사용하던 것과 같이 사용가능합니다.

```ts
enum Events {
  SOME_EVENT = "some_event",
  ANOTHER_EVENT = "another_event",
}

// 이 경우엔 enum 의 key 와 value 가 case(lower/upper) 만 다르고 철자는 같다는 전제가 있어야 하긴 합니다. 
function foo(data: Events | Lowercase<keyof typeof Events>) {
  console.log(data);
}

foo(Events.SOME_EVENT); // OK
foo("another_event"); // OK
foo("invalid_event"); // 컴파일 오류
```
