### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Session closed before response #~~

### ISSUE THREAD

**Issue by ha1fstack** [storycraft/node-kakao#472]
**Describe the bug**
UnhandledPromiseRejectionWarning: Error: Session closed before response #~~
(로그 찍어보면 method PING)
at LocoSession.request (node-kakao/src/network/request-session)
at processTicksAndRejections (internal/process/task_queues)
(추가 스택 없음)

=> 세션이 끊겨서 핑이 실패

**To Reproduce**
로그인 상태 유지시 랜덤하게 발생합니다

```typescript
private addPingHandler() {
  const pingHandler = () => {
    if (!this.logon) return;

    // Error handling
    this.session.request('PING', {}).catch(err=>this.onError(err));
    
    // Fix weird nodejs typing
    this._pingTask = setTimeout(pingHandler, this.pingInterval) as unknown as number;
  };
  pingHandler();
}
```

우선 이렇게 조치해서 재시작되게 했는데
안드로이드 태블릿 클라이언트이고 핑간격은 수동으로 30초로 조절했습니다
세션이 끊기는 이유가 뭘까요?

**Comment by storycraft** [comment]
PING 요청시 오류가 핸들링되지 않는 문제는 20550c9e5a5ef0cfa3301da79fefd7933c32c58b 에서 해결되었습니다. 연결이 끊기는 문제는 안드로이드 태블릿 클라이언트에서 발생하는 문제로 알고 있는데, 기본 pc 클라이언트에서도 해당 오류가 발생하나요?

**Comment by ha1fstack** [comment]
해결했습니다 리눅스 서버 네트워크 문제였네요
저 에러는 핸들 가능하게 하는게 어떨까 합니다

**Comment by kaan03** [comment]
> PING 요청시 오류가 핸들링되지 않는 문제는 [20550c9](https://github.com/storycraft/node-kakao/commit/20550c9e5a5ef0cfa3301da79fefd7933c32c58b) 에서 해결되었습니다. 연결이 끊기는 문제는 안드로이드 태블릿 클라이언트에서 발생하는 문제로 알고 있는데, 기본 pc 클라이언트에서도 해당 오류가 발생하나요?

저 또한 위 오류가 발생하였는데, 수정본은 어떻게 적용하면 되나요?
