### ISSUE TITLE
v3 관련 버그

### ISSUE THREAD

**Issue by cjh980402** [storycraft/node-kakao#51]
1. It cannot recognize new room before re-compile when it's running.
2. It cannot recognize dafalut Group talk name(not open talk) when it's default name like "person1, person2".

**Comment by storycraft** [comment]
1. 재컴파일이 무슨 의미인지 모르겠습니다. 관련 버그는 이미 #49, #38 에 있습니다.
2. 이름이 설정안된 방은 원래 이름이 빈칸이 맞습니다. 해당 형식의 방이름은 3.1(#46)에 추가 계획중인 getDisplayName()으로 생성할 수 있습니다

**Comment by cjh980402** [comment]
답변 감사합니다. 실행 중 새 방이 인식되지 않는데, 봇을 중지한 후 다시 실행을 하면 인식이 된다는 뜻이었습니다.
그리고 이름이 설정이 안 된 방이라는게 정확히는 카톡 목록에서 구성원의 이름만 나열된 기본 이름으로 뜨는 방을 뜻하는 거였습니다. 이 경우도 따로 설정이 안 돼있는거나 마찬가지여서 빈칸으로 되는거군요.

답변 감사합니다.
