### ISSUE TITLE
'TalkChannel' 형식에 'hideChat' 속성이 없습니다.

### ISSUE THREAD

**Issue by kaan03** [storycraft/node-kakao#530]
node-kakao v4 버전 사용중입니다. 
eval을 사용하여 ~sender.perm 이나 ~channel.hideChat() 입력시 오류 없이 작동됩니다만, 이를 코드에 집어넣으려고만 하면 오류가 나면서 컴파일이 안되네요. 소스 내에서 어디를 수정해야 할까요?

import { AuthApiClient, ChatBuilder, KnownChatType, MentionContent, ReplyContent, TalkClient, OpenLinkProfiles, TalkNormalChannel, TalkOpenChannel, OpenLinkProfile, OpenChannelUserPerm } from 'node-kakao';

...

CLIENT.on('chat', (data, channel) => {
  try{
    const sender = data.getSenderInfo(channel);
    if (!sender) return;
    if(sender.perm === 1) {
        channel.sendChat('방장임');
    }
  }catch(e) {}
}

![image](https://user-images.githubusercontent.com/85083657/126805797-41473bab-2992-4203-9396-7638903e598b.png)
![image](https://user-images.githubusercontent.com/85083657/126805635-80b3bc08-e1be-4c43-8e11-731127242be6.png)
![image](https://user-images.githubusercontent.com/85083657/126805884-5f423af4-7150-4823-9193-842bec53d8d4.png)

**Comment by ecclesia00** [comment]
```ts
(chanenl as unknown as TalkOpenChannel).hideChat();
```

**Comment by storycraft** [comment]
TalkClient의 chat 이벤트는 오픈채팅방과 일반채팅방의 chat이벤트가 같이 호출됩니다. https://github.com/storycraft/node-kakao/discussions/320#discussioncomment-744428 위 글을 참고하세요

**Comment by kaan03** [comment]
> TalkClient의 chat 이벤트는 오픈채팅방과 일반채팅방의 chat이벤트가 같이 호출됩니다. [#320 (comment)](https://github.com/storycraft/node-kakao/discussions/320#discussioncomment-744428) 위 글을 참고하세요

감사합니다. 해결되었습니다.
