### ISSUE TITLE
리버싱은 어떻게 하신건가요?

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#6]
리버싱은 어떻게 하신건가요?

**Comment by storycraft** [comment]
이미 이것과 관련해서는 예전에 만들어진 자료들이 있습니다. 특히 [pykakao](https://github.com/hallazzang/pykakao)에서 많은 도움을 받았습니다. 제가 클라이언트를 뜯을정도의 능력은 되지 않기 때문에 나머진 전부 삽질입니다.

**Comment by starlesssss** [comment]
감사합니다. 대단하시네요^^
`
    async kickMem(memberId: Long): Promise<Chat> {
        return new Promise((resolve, reject) => {

            console.log('KICKMEM');
            console.log(this.channelInfo.ChannelClientUser.UserId);
            console.log(this.channelId);
            console.log(memberId);

            //clientopenuserid, channelid, memberid
            let packet = new PacketKickMemberReq(this.channelInfo.ChannelClientUser.UserId, this.channelId, memberId).once('response', (res: PacketMessageWriteRes) => {
                //let chat = this.client.SessionManager!.chatFromChatlog(new ChatlogStruct(res.LogId, res.PrevLogId, this.channelInfo.ChannelClientUser.UserId, this.channelId, MessageType.Text, text, Math.floor(Date.now() / 1000), '', res.MessageId));
                //resolve(chat);
            });
    
            this.client.NetworkManager.sendPacket(packet);
        });
    }
`
혹시 chat-channel에 이런 메소드를 만들어 봤는데요, 패킷 전송은 성공하는데 실제로 강퇴가 안되더라고요. 뭐가 문제인지 살펴봐주실수 있으신가요?

**Comment by storycraft** [comment]
KICKMEM 패킷의 첫번째 인자는 오픈프로필 id지 유저 id가 아닙니다. 이런류의 질문을 이슈트래커에 하는건 최대한 자제해주셨으면 좋겠습니다.
