### ISSUE TITLE
channel_join not emitting

### ISSUE THREAD

**Issue by luftaquila** [storycraft/node-kakao#631]
**Describe the bug**
4.4.0 버전에서 클라이언트가 채팅방에 초대되어도 channel_join 이벤트가 발생하지 않습니다.

**To Reproduce**
CLIENT.on('channel_join', channel => console.log(channel));

**Comment by ghost** [comment]
channel_added로도 해보셨나요?

**Comment by luftaquila** [comment]
@storycraft `channel_added`로 하니까 작동하네요. [examples/events.ts](https://github.com/storycraft/node-kakao/blob/stable/examples/events.ts)에 없어서 이런 키워드가 있는 줄 몰랐네요. 감사합니다.
