### ISSUE TITLE
OpenLinkManager uncaughtException 

### ISSUE THREAD

**Issue by LeeHyKu** [storycraft/node-kakao#66]
**Describe the bug**
OpenLinkManager.get에서 올바르지 않은 id를 입력했을때 uncaughtException 혹은 error; ClientEvent 이벤트가 발생합니다

**To Reproduce**
OpenLinkManager.get(new Long(0,0));

**Expected behavior**
id가 올바르지 않을때 에러를 던져주는게 좋을것 같습니다

**Comment by storycraft** [comment]
해당 id를 가진 오픈링크가 존재하지 않을경우 잘못된 패킷 처리가 이루어져 발생한 문제입니다.
OpenLinkManager의 get 메서드는 getFromURL 메서드와 같이 존재하지 않는 오픈링크에 대해서는 null을 반환합니다.
