### ISSUE TITLE
lacking attachments

### ISSUE THREAD

**Issue by starlesssss** [storycraft/node-kakao#7]
ex) @user (plain text msg type with highlighted mention)
valid attachment:
`
{"mentions":[{"at":[1],"len":4,"user_id":"~~~"}]}
`
not exists in chat.AttachmentList

\+ Do you accept code questions? Where can I ask you?

**Comment by delta-kor** [comment]
In my case, I added rawAttachment property in module ```Chat```.

talk/chat/chat.ts
```javascript
protected processAttachment(rawAttachment: string) {
        if (!rawAttachment || rawAttachment === '') {
            return;
        }

        let json: any = {};

        try {
            json = JSON.parse(rawAttachment);
        } catch(e) {
            
        }

        this.rawAttachment = json;
        this.readAttachment(json, this.attachmentList);
    }
```

**Comment by starlesssss** [comment]
Also, there isn't 'mention' extending class in ChatAttachment.

**Comment by starlesssss** [comment]
I implemented it like this:

@ message-template.ts

```
getMessageType() {
        if (this.attachment) {
            if (this.attachment instanceof MentionAttachment) {
                return MessageType.Text;
            } else if
...
```

@ chat-attachment.ts
```
export class MentionAttachment extends ChatAttachment {

    constructor(
        private mentions: object[] = []
    ) {
        super();
    }

    readAttachment(rawJson: any): void {
        this.mentions = rawJson['k'];
    }
    
    toJsonAttachment() {
        let obj: any = {
            'mentions': this.mentions,
        };

        return obj;
    }

}
```


=>
        let attachment = new MentionAttachment([{
            "at": [1],
            "len": 4,
            "user_id": chat.Sender.UserId.toString()
        }]);
        let attachmentTemplate = new AttachmentTemplate(attachment);
        attachmentTemplate.Text = '@user 안녕'
        chat.replyTemplate(attachmentTemplate);

**Comment by storycraft** [comment]
These attachments are selected by message type. Mentions and link(url highlight) contents are individual things and should be processed by another function rather than 'readAttachment'. 
```js
this.readAttachment(json, this.attachmentList);
```
^this

ReplyChat and ReplyAttachment are planned to future commit.

**Comment by starlesssss** [comment]
> I implemented it like this:
> 
> @ message-template.ts
> 
> ```
> getMessageType() {
>         if (this.attachment) {
>             if (this.attachment instanceof MentionAttachment) {
>                 return MessageType.Text;
>             } else if
> ...
> ```
> 
> @ chat-attachment.ts
> 
> ```
> export class MentionAttachment extends ChatAttachment {
> 
>     constructor(
>         private mentions: object[] = []
>     ) {
>         super();
>     }
> 
>     readAttachment(rawJson: any): void {
>         this.mentions = rawJson['mentions'];
>     }
>     
>     toJsonAttachment() {
>         let obj: any = {
>             'mentions': this.mentions,
>         };
> 
>         return obj;
>     }
> 
> }
> ```
> 
> =>
> 
> ```
> let attachment = new MentionAttachment([{
>     "at": [1],
>     "len": chat.Sender.UserInfo.Nickname.length,
>     "user_id": chat.Sender.UserId.toString()
> }]);
> let attachmentTemplate = new AttachmentTemplate(attachment);
> attachmentTemplate.Text = `@${chat.Sender.UserInfo.Nickname} 안녕하세요`
> chat.replyTemplate(attachmentTemplate);
> chat.replyText('안녕하세요');
> ```

말이 길어져서 한글로 쓰겠습니다.
해당 메소드를 적용해보니 오류가 있는데, 채팅이 이상하게 반응합니다.
예를 들어
chat.replyTemplate(attachmentTemplate);
chat.replyText('안녕하세요');
이렇게 메세지를 연속해서 두번 보내면 아무 문제가 없는데,
chat.replyTemplate(attachmentTemplate);
만 보내면 특정 클라이언트에서는 메세지가 보이고, 특정 클라이언트에서는 메세지가 안보이다가 몆건의 다른 메세지를 더 보내면 갑자기 나타나고 중간에 꼬이게 되네요. 뭐가 문제인지 아시나요?

**Comment by storycraft** [comment]
해당 코드는 현재 구현된 추가된 부분이 아니기 때문에 잘 모르겠지만 user_id 값은 string 타입이 아니라 Long 타입으로 추정됩니다.

**Comment by starlesssss** [comment]
Long으로 직접 넣으면 작동하지 않고 int로 하면 정수범위를 초과해서 str으로 했는데 문제 없이 작동됩니다
혹시 채팅을 보낸 후에 해당 채팅이 보내졌다는 사실을 별도로 서버에 보내주던가 해야되는건가요?

**Comment by starlesssss** [comment]
맞네요 string으로 넣으면 되긴 하는데 위처럼 이상한 오류가 생깁니다.
user_id가 정수범위를 초과하지 않는 봇 계정 자신의 user_id를 넣으면 정상적으로 되고
그렇다고 string 말고 toInt로 해서 넣으면 정수범위를 초과해서 제대로 멘션이 안되네요. 제대로 멘션이 안될때에도 '이상한 현상'은 나타나고, 그냥 임의로 정수범위 이내의 아무 숫자를 넣으면 역시 멘션은 제대로 안되지만 이상한 현상은 안일어나네요. 어떻게 해야 할까요?

**Comment by storycraft** [comment]
Implemented in 032e9c71693f9058c3c5bf0b8bceb14caeec011c.
