### ISSUE TITLE
질문있습니다

### ISSUE THREAD

**Issue by runkan** [storycraft/node-kakao#74]
let client = new TalkClient('TEST_CLIENT', 'random base64 device id');

이부분이 잘 이해가 안되는데

TEST_CLIENT와 tandom base64 device id 에는 무엇을 넣어야하는지, 어떻게 가져오는지 궁금합니다

**Comment by txrx0031** [comment]
TEST_CLIENT에는 로그인할 PC클라이언트 이름을, uuid에는 본인의 디바이스 uuid를 삽입하세요
. 
(device uuid는 base64로 인코딩되어 있는 아무 문자열이라도 가능합니다.)
