### ISSUE TITLE
Null is returned when using chat.channel.getUserInfo() in an Open Group chat with more than 1000 people.

### ISSUE THREAD

**Issue by kiwioverflow** [storycraft/node-kakao#75]
**Describe the bug**
Null is returned when using `chat.channel.getUserInfo()` in an Open Gruop chat with more than 1000 people.

**To Reproduce**
Run the code `chat.channel.getUserInfo(chat.sender)`  on a chat room with more than 1000 people, null will be returned.

**Expected behavior**
It should return information about `chat.sender`.

**Comment by kiwioverflow** [comment]
👍👍👍

**Comment by magenta1028** [comment]
👍👍👍
