### ISSUE TITLE
Client does not receive packet without any sign after some time from login

### ISSUE THREAD

**Issue by ha1fstack** [storycraft/node-kakao#773]
**Describe the bug**
Same issue with #391.
Client does not receive packet without any sign after some time from login.
This behavior is not detected by listener events (disconnect, error, push_packet, etc...) .
100% reproduceable in certain unknown conditions, might be server side thing but not very sure.
Looking for specific conditions or reasons when/why the behavior occurs.

**To Reproduce**
idk, looking for answer

**Expected behavior**
Client should work as intended.

**Comment by storycraft** [comment]
This unknown behavior can be reproduced when the client is running very long time. Maybe something like timeout being ignored by promise-socket.

**Comment by ha1fstack** [comment]
IDK the exact reason but it can happen only after about few minutes.
maybe related to #775 - might be happening after receiving malformed reply chat?

edit: maybe happens when a lot of requests sent in short time from client side?
