### ISSUE TITLE
msg packets randomly skipped when on extreme load

### ISSUE THREAD

**Issue by ha1fstack** [storycraft/node-kakao#778]

**Comment by kiwioverflow** [comment]
How fast should the message come to be omitted?
and If executing the syncChatList method, does it include a missing message?

**Comment by ha1fstack** [comment]
> How fast should the message come to be omitted? and If executing the syncChatList method, does it include a missing message?

1. idk, you never experienced similar problem?
2. yes

**Comment by disabled-variable** [comment]
Please give me a code to reproduce the problem.
I'll test it out.
