### ISSUE TITLE
general improvement suggestion: handling request packet response

### ISSUE THREAD

**Issue by ha1fstack** [storycraft/node-kakao#779]
*excuse me for ignoring the issue template

Currently node-kakao has little support for request packet handling.

**1. event listener for outgoing packet**
There is incoming push packet event listener, then why not outgoing packet listener? It might be useful for debugging and some special use cases.

**2. all response data packet request that returns data - especially those including chatLog - should be handled.**
For example, 'REWRITE' packet (or hideChat method) response is handled as DefaultRes and returns only status. However it actually returns full chatLog data.
```
id: 0,
push: false,
method: 'REWRITE',
data: {
  status: 0,
  errMsg: null,
  chatLog: {
    logId: new Long("1234123412341234123"),
    prevId: new Long("1234123412341234123"),
    chatId: new Long("1234123412341234123"),
    type: 0,
    authorId: new Long("1234567890"),
    message: '{"feedType":13,"logId":1234123412341234123,"type":26}',
    sendAt: 1636000000,
    msgId: 0
  }
}
```
So there is no way to access chatLog generated by REWRITE request. Full response data should be handled.

**3-0. chatListStore issue**
maybe this should be an separated issue?
UpdatableChatListStore or TalkMemoryChatListStore has addChat method.
addChat method does not check duplicate.
TalkChannelDataSession's public method syncChatList and getChatListFrom calls addChat method.
Since it's public method these can be manually called by user for certain applications.
syncChatList is also used internally to fill missing chats.
so when user calls these methods manually to retrieve chat, addChat is called and duplicates are pushed to chatListStore.
Thus addChat should have internal duplicate filter and internal method(called by client) / external method(called by user) should be separated to prevent unnecessary tasks.

**3. chatListStore should be 100% synced in real time with syncChatList/getChatListFrom request result.**
Extension of 2.
chatListStore should contain same contents with chatlog response data from server.
all incoming push packets and outgoing msg packets are handled, but outgoing feeds are not 100% handled. (ex: hide chat => type: 0, feed: 13, present in chatlog from server, but not handled when requested.)
client sent feeds should be included in chatListStore. (also lastChatLogId, lastChatLog should be updated.)

**Comment by storycraft** [comment]
1. Use `HookedSessionFactory` for debugging incoming / outgoing packets. You can inspect every packets using it. Example code would be like this.
```typescript
const mainClient = new TalkClient(
  {},
  TalkInMemoryDataLoader,
  new HookedSessionFactory(
    new TalkSessionFactory(),
    {
      onData: (method, data, push) => { // Hook incoming data
        if (method == 'MSG') {
          console.log('MSG: ' + inspect(data, true, 5, true));
        }
      },
      onRequest: (method, data) => { // Hook outgoing data
        
      }
    }
  )
);
```
Also see https://github.com/storycraft/node-kakao/blob/stable/src/hook/session-factory-hook.ts

2. I only implemented packet typing mostly when the client need to handle it (some are not). The DefaultRes is dictonary with unknown type. So code below works.
```typescript
function handle(data: DefaultRes) {
  const struct = data['chatLog'] as ChatlogStruct;
  const chatLog = structToChatlog(struct);
}
```
For hideChat response I think the response should be handled.

3. The only reason that chat store and channel store exist is complexity. It is too hard to maintain channel user data, chat data manually. The official client only request user data when initializing, clicking profile, request channel data only when initializing, opening chat channel window and updates data using many other packets with different .

The default Inmemory store designed to store only recent data to optimize memory usage. `node-kakao-db` extension stores every chats and can handle duplicate chats and sync missing chats on login using sqlite.

I have future version update planned but I lost interests. I can't sure when issue will be fixed.
