### ISSUE TITLE
보안인증 시에 -500 반환

### ISSUE THREAD

**Issue by paring-chan** [storycraft/node-kakao#790]
**Describe the bug**
Ex) Reading CustomAttachment crashes client.

examples/device-registration 실행 시 보안인증이 작동하지 않습니다.
**To Reproduce**

run examples/device-registration.ts

**Expected behavior**

response with success: true

**Screenshots**
![image](https://user-images.githubusercontent.com/68010770/140592514-39ff1353-a8c7-4ec0-853a-5ceda06eea3c.png)

**Comment by wngks1232** [comment]
때려 박으면 되요
