### ISSUE TITLE
카카오톡 운영정책 변경

### ISSUE THREAD

**Issue by DeltaLaboratory** [storycraft/node-kakao#800]
[2021년 12월 7일부터 적용되는 개정된 운영정책](http://kko.to/KQULO7Z4B)에 의하면,

- 프로그램코드 역분석을 통하여 얻은 정보를 제 3 자에게 제공·공개하는 행위 [P37L4]
- 카카오가 허용하지 않은 비정상적인 프로그램 등을 이용하여 카카오톡의 프로토콜·API 등을 부정하게
호출하는 행위 [P37L9]
- 카카오톡의 프로토콜·API 등을 악용한 프로그램(봇, 매크로, 웹사이트 등)을 개발·제작하여 이를 유상 또는 무상으로 타인에게 유포·제공하는 행위 [P37L12]

등을 금지하고 있습니다.
상기 운영정책에 따르면, 이 라이브러리는 카카오 운영정책에 위배됩니다.
이에 따른 대책이 있으시거나, 이 라이브러리를 삭제할 의향이 있으십니까?

**Comment by ANEP-Research** [comment]
해당 주장에 대해서 반론이 있습니다.
[P37L4] 본 라이브리리 소스코드를 일종의 정보로 봐서 해당된다고 볼 수도 있겠지만, '프로그램코드 역분석'이라는 것은 보통 Ghidra 등의 툴로 분석하는 것을 의미합니다. 이 라이브러리에서는 이러한 API 호출 관계를 어디에서 얻었는지 그러한 부분을 명시하지도 않았고, 이런 호출 관계를 얻는 방법은 '프로그램코드 역분석' 외에도 패킷스니핑 등의 방식이 존재하여 해당한다고 보기에는 모호합니다.
[P37L9] 라이브러리를 제공하는것과 라이브러리를 이용하여 프로그램을 제작하여 API를 호출하는 것은 별개의 관계입니다.
[P37L12] node-kakao는 라이브러리일뿐이지, 프로그램이 아닙니다.

**Comment by DeltaLaboratory** [comment]
>  해당 주장에 대해서 반론이 있습니다. [P37L4] 본 라이브리리 소스코드를 일종의 정보로 봐서 해당된다고 볼 수도 있겠지만, '프로그램코드 역분석'이라는 것은 보통 Ghidra 등의 툴로 분석하는 것을 의미합니다. 이 라이브러리에서는 이러한 API 호출 관계를 어디에서 얻었는지 그러한 부분을 명시하지도 않았고, 이런 호출 관계를 얻는 방법은 '프로그램코드 역분석' 외에도 패킷스니핑 등의 방식이 존재하여 해당한다고 보기에는 모호합니다. [P37L9] 라이브러리를 제공하는것과 라이브러리를 이용하여 프로그램을 제작하여 API를 호출하는 것은 별개의 관계입니다. [P37L12] node-kakao는 라이브러리일뿐이지, 프로그램이 아닙니다.

1. 카카오톡은 Api에 HTTPS를 사용중이고, Loco Protocol은 AES 암호화를 사용중입니다. 모든 정보와 형식은 암호화되어 전송되기때문에 스니핑으로 필요한 정보를 얻는것은 불가능합니다.
  : https://github.com/storycraft/node-kakao#basic-reference
     노드 카카오 자체가 역분석을 통한 정보를 사용하였다고 명시하고 있습니다.
  추가로 다른 라이브러리에서 리버싱을 사용하지 않았다고 하는 경우가 발생했는데, 메모리 상에 올라가있는 정보를 타 프로그램에서 강제로 읽는것은 리버싱이라고 간주될 수 있습니다
2. 그렇게 생각할 수 있는 부분입니다.
3. 라이브러리도 프로그램의 한 분류입니다.

**Comment by storycraft** [comment]
> [2021년 12월 7일부터 적용되는 개정된 운영정책](http://kko.to/KQULO7Z4B)에 의하면,
> 
> * 프로그램코드 역분석을 통하여 얻은 정보를 제 3 자에게 제공·공개하는 행위 [P37L4]
> * 카카오가 허용하지 않은 비정상적인 프로그램 등을 이용하여 카카오톡의 프로토콜·API 등을 부정하게
>   호출하는 행위 [P37L9]
> * 카카오톡의 프로토콜·API 등을 악용한 프로그램(봇, 매크로, 웹사이트 등)을 개발·제작하여 이를 유상 또는 무상으로 타인에게 유포·제공하는 행위 [P37L12]
> 
> 등을 금지하고 있습니다. 상기 운영정책에 따르면, 이 라이브러리는 카카오 운영정책에 위배됩니다. 이에 따른 대책이 있으시거나, 이 라이브러리를 삭제할 의향이 있으십니까?

본 저장소에서는 특정 소프트웨어가 사용하는 기술을 구현한 것 을 소스코드 형태로 제공하고 있으며, 특정한 목적을 가진 프로그램으로써 배포 / 공유 하고 있지 않습니다. 또한 이것을 사용하여 소프트웨어, 매크로, 웹사이트등을 개발하는 것에 그 어떠한 책임도 지지 않습니다. 이 부분은 저장소내 `LICENSE` 파일 그리고 https://github.com/storycraft/node-kakao/blob/e1a627ffc5031010c2d0224e28103ec85eb5595b/LICENSE 에 명시되어있습니다.

만약 해당 저장소내에 `카카오톡`에서 사용하고 있는 텍스트 또는 코드가 존재 할 경우 이에 대한 권리를 갖고 있는 `저작자 또는 저작권자`는 storycraft@pancake.sh 또는 본 저장소 Pull requests 를 통해 해당 내용이 제거된 패치를 보낼 수 있습니다.
