### ISSUE TITLE
uploadAttachment가 Request에 실패했습니다.

### ISSUE THREAD

**Issue by magenta1028** [storycraft/node-kakao#82]
**Describe the bug**
uploadAttachment가 Request에 실패합니다. (Status Code 500)
`(node:10348) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500`

**To Reproduce**
```javascript
const node_kakao = require("node-kakao");
const fs = require("fs");

async function uploadTest() {
    const photoAttachment = await node_kakao.PhotoAttachment.fromBuffer(fs.readFileSync("./image.png"), "image", 231, 370);
    console.log(photoAttachment);
}

uploadTest();
```

**Expected behavior**
uploadAttachment가 다시 작동할것을 기대합니다.

사용된 사진:
![image](https://user-images.githubusercontent.com/74944468/101955830-e0fab680-3c41-11eb-9dbc-a4c38dc92261.png)

**Comment by storycraft** [comment]
`PhotoAttachment.fromBufter` 메서드는 현재 deprecated 상태이며 다음 버전에서 제거될 예정입니다.  Attachment는 `client.ChatManager.sendMedia` 메서드를 사용하여 바로 보낼수 있습니다. readme에 있는 사진 보내기 예제를 참고하세요.

**Comment by magenta1028** [comment]
`LongAttachment.fromText` 및 `LongAttachment.fromBuffer`도 삭제되나요? 삭제된다면 어떻게 전송할 수 있나요?

**Comment by storycraft** [comment]
sendMedia메서드에서 템플릿 객체의 type을 ChatType.Text로 주는 것으로 텍스트 Buffer 전송이 가능합니다. 사진과 동영상 전송시에만 예제 처럼 width, height이 필요합니다.

**Comment by magenta1028** [comment]
감사합니다.
