### ISSUE TITLE
Unknown file extension ".ts"

### ISSUE THREAD

**Issue by ghost** [storycraft/node-kakao#84]
**Describe the bug**
When I run this module in JavaScript, it works, but when I run it in TypeScript, a problem arises that the ts file is not suitable

**To Reproduce**

1. Import the example source as it is (TS)

2. When run from TS, an error occurs (error in title)

3. It works very well when I run it in JavaScript.

**Expected behavior**
Works very well with typescript files

**Screenshots**
Umm.. Log is 
/usr/local/bin/node ./build.ts
Process exited with code 1
Uncaught TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/user/Desktop/node-kakao/build.ts

**Comment by storycraft** [comment]
To learn about Typescript, see [https://www.typescriptlang.org/](https://www.typescriptlang.org/)

**Comment by storycraft** [comment]
Closing as invalid
