### ISSUE TITLE
sendMedia 메소드 에러

### ISSUE THREAD

**Issue by cjh980402** [storycraft/node-kakao#99]
**Describe the bug**
Ex) 오픈채팅에서 sendMedia를 이용한 장문 전송 시 -500 에러 발생.
정확히는 await chat.Channel.sendMedia({name:"", type:LOCO.ChatType.Text,data:Buffer.from(a)}) 을 할때
a.codePointAt(4009)가 a.charCodeAt(4009)과 다른 경우
(4010자에서 2글자 이상의 js string으로 이루어진 이모티콘이 들어가서 끊긴 경우)

**Expected behavior**
Ex) -500 에러 없이 전송이 돼야함

**Screenshots**

**Comment by cjh980402** [comment]
예시 문자열
a가 (" " + "👍".repeat(2100))인 경우

**Comment by storycraft** [comment]
해당코드의 name 키 값이 빈 문자열입니다

**Comment by cjh980402** [comment]
name에  "text"등의 비어있지 않은 문자열을 사용하여도 동일한 에러가 발생합니다.

**Comment by storycraft** [comment]
재확인 결과 해당 코드에서 잘 작동합니다.
```js
chat.replyMedia({
    name: 'test.txt',
    data: Buffer.from(" " + "👍".repeat(4010)),
    type: ChatType.Text
});
```
위 에러는 인코딩 문제일 가능성이 높아보입니다.

**Comment by cjh980402** [comment]
해당 코드를 복사 후 똑같이 실행하였는데도
```
const sendChat = await chat.replyMedia({
    name: 'test.txt',
    data: Buffer.from(" " + "👍".repeat(4010)),
    type: ChatType.Text
});
```
를 하면 -500이라는 에러가 반환됩니다.

**Comment by txrx0031** [comment]
정상 작동을 확인하였습니다. data 인코딩을 확인해보세요.  (utf-8 등으로 설정후 시도해보세요)

exam) 
```js
chat.replyMedia({
    name: 'test.txt',
    data: Buffer.from(" " + "👍".repeat(4010), "utf-8"),
    type: ChatType.Text
});
```

**Comment by cjh980402** [comment]
채팅 자체는 전송은 되긴 하지만 chat.replyMedia가 반환하는 프로미스 객체를 await로 받으면 -500이라는 에러가 반환되는 현상입니다.

**Comment by storycraft** [comment]
await 사용시 잘 작동하는것 확인했습니다. chat.replyMedia 메서드는 Chat 객체 또는 null을 resolve하는 Promise 객체이기 때문에 해당 객체에서는 -500 에러를 받을 수 없습니다.

**Comment by txrx0031** [comment]
2일이상 추가적인 커멘트가 없어 이슈를 닫겠습니다.
